// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(admin-auth)/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/(admin-auth)/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin-shell)/admin/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/logs">> = Specific
  const handler = {} as typeof import("../../app/(admin-shell)/admin/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin-shell)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(admin-shell)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin-shell)/admin/platforms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platforms">> = Specific
  const handler = {} as typeof import("../../app/(admin-shell)/admin/platforms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin-shell)/admin/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/providers">> = Specific
  const handler = {} as typeof import("../../app/(admin-shell)/admin/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin-shell)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/(admin-shell)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(user-auth)/user/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/login">> = Specific
  const handler = {} as typeof import("../../app/(user-auth)/user/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(user-shell)/user/connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/connections">> = Specific
  const handler = {} as typeof import("../../app/(user-shell)/user/connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(user-shell)/user/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/consent">> = Specific
  const handler = {} as typeof import("../../app/(user-shell)/user/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(user-shell)/user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user">> = Specific
  const handler = {} as typeof import("../../app/(user-shell)/user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(user-shell)/user/platforms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/platforms">> = Specific
  const handler = {} as typeof import("../../app/(user-shell)/user/platforms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(user-shell)/user/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/providers">> = Specific
  const handler = {} as typeof import("../../app/(user-shell)/user/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(user-shell)/user/verification/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/verification/[id]">> = Specific
  const handler = {} as typeof import("../../app/(user-shell)/user/verification/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/client-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client-demo">> = Specific
  const handler = {} as typeof import("../../app/client-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/admin/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/platforms/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/platforms/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/platforms/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/platforms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/platforms">> = Specific
  const handler = {} as typeof import("../../app/api/admin/platforms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers">> = Specific
  const handler = {} as typeof import("../../app/api/admin/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/client/exchange-proof/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/exchange-proof">> = Specific
  const handler = {} as typeof import("../../app/api/client/exchange-proof/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/client/request-age-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/request-age-check">> = Specific
  const handler = {} as typeof import("../../app/api/client/request-age-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/client/session-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/session-status">> = Specific
  const handler = {} as typeof import("../../app/api/client/session-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/connections/[id]/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/connections/[id]/revoke">> = Specific
  const handler = {} as typeof import("../../app/api/user/connections/[id]/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/connections">> = Specific
  const handler = {} as typeof import("../../app/api/user/connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/consent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/consent">> = Specific
  const handler = {} as typeof import("../../app/api/user/consent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/platforms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/platforms">> = Specific
  const handler = {} as typeof import("../../app/api/user/platforms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/providers">> = Specific
  const handler = {} as typeof import("../../app/api/user/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/verify">> = Specific
  const handler = {} as typeof import("../../app/api/user/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verification/[id]/callback/provider/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification/[id]/callback/provider">> = Specific
  const handler = {} as typeof import("../../app/api/verification/[id]/callback/provider/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verification/[id]/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification/[id]/finalize">> = Specific
  const handler = {} as typeof import("../../app/api/verification/[id]/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verification/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/verification/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verification/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification/start">> = Specific
  const handler = {} as typeof import("../../app/api/verification/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(admin-shell)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(admin-shell)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(user-shell)/user/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/user">> = Specific
  const handler = {} as typeof import("../../app/(user-shell)/user/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
