// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/login" | "/admin/logs" | "/admin/platforms" | "/admin/providers" | "/admin/users" | "/client-demo" | "/user" | "/user/connections" | "/user/consent" | "/user/login" | "/user/platforms" | "/user/providers" | "/user/verification/[id]"
type AppRouteHandlerRoutes = "/api/admin/dashboard" | "/api/admin/login" | "/api/admin/logout" | "/api/admin/logs" | "/api/admin/platforms" | "/api/admin/platforms/[id]/status" | "/api/admin/providers" | "/api/admin/users" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/client/exchange-proof" | "/api/client/request-age-check" | "/api/client/session-status" | "/api/user/connections" | "/api/user/connections/[id]/revoke" | "/api/user/consent" | "/api/user/platforms" | "/api/user/providers" | "/api/user/verify" | "/api/verification/[id]/callback/provider" | "/api/verification/[id]/finalize" | "/api/verification/[id]/status" | "/api/verification/start"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/user"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/login": {}
  "/admin/logs": {}
  "/admin/platforms": {}
  "/admin/providers": {}
  "/admin/users": {}
  "/api/admin/dashboard": {}
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/admin/logs": {}
  "/api/admin/platforms": {}
  "/api/admin/platforms/[id]/status": { "id": string; }
  "/api/admin/providers": {}
  "/api/admin/users": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/client/exchange-proof": {}
  "/api/client/request-age-check": {}
  "/api/client/session-status": {}
  "/api/user/connections": {}
  "/api/user/connections/[id]/revoke": { "id": string; }
  "/api/user/consent": {}
  "/api/user/platforms": {}
  "/api/user/providers": {}
  "/api/user/verify": {}
  "/api/verification/[id]/callback/provider": { "id": string; }
  "/api/verification/[id]/finalize": { "id": string; }
  "/api/verification/[id]/status": { "id": string; }
  "/api/verification/start": {}
  "/client-demo": {}
  "/user": {}
  "/user/connections": {}
  "/user/consent": {}
  "/user/login": {}
  "/user/platforms": {}
  "/user/providers": {}
  "/user/verification/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/user": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
